# Loading and Preprocessing

In [ ]:
from data_loader import load_data

In [2]:
X_clinical,\
X_clinical_A,\
X_clinical_B,\
X_clinical_Delta,\
targets,\
clinical_numeric_cols,\
num_cols,\
cat_cols = load_data(combined=True)

In [3]:
targets.head()

,surv_bestresponse_car,ae_summ_icans_v2,ae_summ_icans_highestgrade_v2,ae_summ_crs_v2,ae_summ_highestgrade_v2
record_id,,,,,
FTC-EMC-0022,1.0,0.0,0.0,0.0,0.0
FTC-EMC-0023,2.0,1.0,4.0,1.0,2.0
FTC-EMC-0027,4.0,1.0,1.0,1.0,2.0
FTC-UMCG-0001,1.0,1.0,1.0,1.0,1.0
FTC-UMCG-0003,4.0,0.0,0.0,1.0,1.0

In [ ]:
# Using ColumnTransformer to apply different transformations to numeric and categorical columns
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

# Create a ColumnTransformer to apply StandardScaler to numeric columns and leave categorical columns unchanged
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('cat', 'passthrough', cat_cols)
    ]
)

preprocessor_clinical_only = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), clinical_numeric_cols),
        ('cat', 'passthrough', cat_cols)
    ]
)

In [5]:
datasets = {
    "Clinical": X_clinical,
    "Clinical_A": X_clinical_A,
    "Clinical_B": X_clinical_B,
    "Clinical_Delta": X_clinical_Delta
}

In [6]:
preprocessors = [preprocessor_clinical_only, preprocessor]

In [7]:
from model_eval import result_viewer

# ICANS 0,1

In [8]:
y = targets['ae_summ_icans_v2']

In [9]:
y.value_counts()

ae_summ_icans_v2
1.0    48
0.0    37
Name: count, dtype: int64

In [10]:
icans_1 = result_viewer(preprocessors, datasets, y)

Results for Logistic Regression:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.6219 ± 0.1687,0.6075 ± 0.1070,0.5010 ± 0.1355,0.4306 ± 0.1066
train_roc_auc,0.9182 ± 0.0321,0.9981 ± 0.0012,0.9993 ± 0.0014,1.0000 ± 0.0000
test_precision,0.6981 ± 0.1533,0.6339 ± 0.0735,0.5906 ± 0.0716,0.5441 ± 0.0499
train_precision,0.8475 ± 0.0386,0.9741 ± 0.0162,0.9749 ± 0.0224,1.0000 ± 0.0000
test_recall,0.7333 ± 0.1313,0.7311 ± 0.1456,0.7311 ± 0.0799,0.6289 ± 0.1280
train_recall,0.8958 ± 0.0441,0.9740 ± 0.0166,0.9949 ± 0.0103,0.9949 ± 0.0103
test_f1,0.7007 ± 0.0906,0.6696 ± 0.0630,0.6482 ± 0.0434,0.5781 ± 0.0764
train_f1,0.8708 ± 0.0395,0.9740 ± 0.0144,0.9847 ± 0.0148,0.9974 ± 0.0052

Results for Decision Tree:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.6164 ± 0.1377,0.4981 ± 0.1416,0.6160 ± 0.1296,0.5615 ± 0.1587
train_roc_auc,0.8036 ± 0.0371,0.8133 ± 0.0473,0.8386 ± 0.0227,0.8418 ± 0.0169
test_precision,0.6320 ± 0.0722,0.5576 ± 0.0987,0.6126 ± 0.0686,0.7139 ± 0.2559
train_precision,0.7445 ± 0.0536,0.7826 ± 0.0457,0.7842 ± 0.0847,0.8549 ± 0.0797
test_recall,0.7378 ± 0.1836,0.6289 ± 0.1280,0.8356 ± 0.1372,0.5244 ± 0.3014
train_recall,0.9059 ± 0.0395,0.8958 ± 0.0469,0.9013 ± 0.0820,0.8132 ± 0.1672
test_f1,0.6694 ± 0.0929,0.5883 ± 0.1080,0.7006 ± 0.0709,0.5394 ± 0.1956
train_f1,0.8156 ± 0.0304,0.8333 ± 0.0199,0.8308 ± 0.0230,0.8143 ± 0.0725

Results for Random Forest:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.6213 ± 0.0656,0.4842 ± 0.1581,0.6652 ± 0.1630,0.5847 ± 0.0558
train_roc_auc,0.9514 ± 0.0137,0.9557 ± 0.0132,0.9838 ± 0.0065,0.9915 ± 0.0038
test_precision,0.6000 ± 0.0404,0.5269 ± 0.0574,0.6282 ± 0.0616,0.6070 ± 0.0600
train_precision,0.7964 ± 0.0292,0.8063 ± 0.0353,0.8659 ± 0.0263,0.8609 ± 0.0550
test_recall,0.8000 ± 0.1897,0.7511 ± 0.1599,0.8311 ± 0.1643,0.8400 ± 0.1625
train_recall,0.9479 ± 0.0167,0.9634 ± 0.0131,1.0000 ± 0.0000,0.9947 ± 0.0105
test_f1,0.6718 ± 0.0671,0.6147 ± 0.0806,0.7017 ± 0.0560,0.6925 ± 0.0503
train_f1,0.8651 ± 0.0162,0.8774 ± 0.0196,0.9279 ± 0.0151,0.9220 ± 0.0314

## ICANS >=2

In [11]:
y = targets["ae_summ_icans_highestgrade_v2"]

In [12]:
y = y.astype('int8')

In [13]:
y[y<2] = 0
y[y>=2] = 1

In [14]:
y.value_counts()

ae_summ_icans_highestgrade_v2
0    52
1    33
Name: count, dtype: int64

In [15]:
icans_2 = result_viewer(preprocessors, datasets, y)

Results for Logistic Regression:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.6740 ± 0.1301,0.6115 ± 0.1322,0.6155 ± 0.1194,0.6072 ± 0.1650
train_roc_auc,0.9264 ± 0.0231,0.9973 ± 0.0034,0.9996 ± 0.0007,0.9978 ± 0.0031
test_precision,0.5457 ± 0.2386,0.5467 ± 0.1614,0.5436 ± 0.2399,0.5702 ± 0.1239
train_precision,0.8504 ± 0.0616,0.9775 ± 0.0298,0.9929 ± 0.0143,1.0000 ± 0.0000
test_recall,0.4619 ± 0.1779,0.5524 ± 0.1666,0.5000 ± 0.2966,0.6190 ± 0.2228
train_recall,0.7419 ± 0.0933,0.9775 ± 0.0298,0.9772 ± 0.0186,0.9627 ± 0.0406
test_f1,0.4649 ± 0.1723,0.5348 ± 0.1409,0.4269 ± 0.1693,0.5625 ± 0.1345
train_f1,0.7911 ± 0.0783,0.9775 ± 0.0298,0.9847 ± 0.0076,0.9805 ± 0.0215

Results for Decision Tree:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.5519 ± 0.1120,0.5630 ± 0.1350,0.5211 ± 0.0574,0.5686 ± 0.1133
train_roc_auc,0.7618 ± 0.0458,0.8001 ± 0.0644,0.8065 ± 0.0406,0.8183 ± 0.0413
test_precision,0.4524 ± 0.1242,0.4113 ± 0.0792,0.5222 ± 0.2475,0.4058 ± 0.0943
train_precision,0.8161 ± 0.1582,0.7398 ± 0.1372,0.7776 ± 0.1416,0.8272 ± 0.1248
test_recall,0.3714 ± 0.1741,0.4667 ± 0.3003,0.3095 ± 0.2087,0.5048 ± 0.2683
train_recall,0.5242 ± 0.1690,0.7707 ± 0.1971,0.7037 ± 0.1511,0.7014 ± 0.1921
test_f1,0.3762 ± 0.0930,0.4154 ± 0.1745,0.3334 ± 0.1368,0.4363 ± 0.1587
train_f1,0.5994 ± 0.1220,0.7246 ± 0.0836,0.7103 ± 0.0336,0.7250 ± 0.0691

Results for Random Forest:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.6352 ± 0.1620,0.5181 ± 0.1943,0.6195 ± 0.1478,0.4074 ± 0.0991
train_roc_auc,0.9652 ± 0.0115,0.9883 ± 0.0034,0.9733 ± 0.0064,0.9938 ± 0.0081
test_precision,0.3000 ± 0.4000,0.0667 ± 0.1333,0.7167 ± 0.2667,0.1667 ± 0.2108
train_precision,0.9818 ± 0.0364,1.0000 ± 0.0000,0.9631 ± 0.0304,1.0000 ± 0.0000
test_recall,0.0952 ± 0.1313,0.0333 ± 0.0667,0.2762 ± 0.1555,0.0952 ± 0.1313
train_recall,0.4234 ± 0.0901,0.4855 ± 0.1008,0.5601 ± 0.0354,0.6137 ± 0.0654
test_f1,0.1444 ± 0.1975,0.0444 ± 0.0889,0.3813 ± 0.1877,0.1200 ± 0.1600
train_f1,0.5860 ± 0.0949,0.6474 ± 0.0923,0.7072 ± 0.0250,0.7585 ± 0.0518

# CRS 0,1

In [16]:
y = targets["ae_summ_crs_v2"]

In [17]:
y.value_counts()

ae_summ_crs_v2
1.0    79
0.0     6
Name: count, dtype: int64

In [18]:
crs_1 = result_viewer(preprocessors, datasets, y)

Results for Logistic Regression:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.4767 ± 0.1307,0.2133 ± 0.2200,0.4008 ± 0.1886,0.2692 ± 0.1558
train_roc_auc,0.9956 ± 0.0043,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000
test_precision,0.9249 ± 0.0251,0.9254 ± 0.0219,0.9287 ± 0.0232,0.9248 ± 0.0213
train_precision,0.9635 ± 0.0070,1.0000 ± 0.0000,0.9938 ± 0.0077,0.9938 ± 0.0076
test_recall,0.9367 ± 0.0396,0.9375 ± 0.0685,0.9875 ± 0.0250,0.9250 ± 0.0468
train_recall,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000
test_f1,0.9302 ± 0.0250,0.9298 ± 0.0339,0.9568 ± 0.0158,0.9238 ± 0.0168
train_f1,0.9814 ± 0.0037,1.0000 ± 0.0000,0.9969 ± 0.0039,0.9969 ± 0.0038

Results for Decision Tree:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.4179 ± 0.0314,0.4500 ± 0.0612,0.3171 ± 0.2522,0.4000 ± 0.0606
train_roc_auc,0.8396 ± 0.0697,0.8741 ± 0.0959,0.9411 ± 0.0445,0.8329 ± 0.1060
test_precision,0.9207 ± 0.0272,0.9214 ± 0.0209,0.9372 ± 0.0046,0.9233 ± 0.0217
train_precision,0.9577 ± 0.0170,0.9815 ± 0.0148,0.9844 ± 0.0001,0.9606 ± 0.0117
test_recall,0.8858 ± 0.0473,0.8875 ± 0.1146,0.9483 ± 0.0495,0.9125 ± 0.1090
train_recall,0.9937 ± 0.0077,0.9937 ± 0.0078,1.0000 ± 0.0000,1.0000 ± 0.0000
test_f1,0.9023 ± 0.0317,0.9000 ± 0.0603,0.9422 ± 0.0270,0.9142 ± 0.0574
train_f1,0.9752 ± 0.0056,0.9874 ± 0.0062,0.9922 ± 0.0000,0.9799 ± 0.0061

Results for Random Forest:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.4700 ± 0.0944,0.4400 ± 0.1896,0.4233 ± 0.3569,0.1583 ± 0.1219
train_roc_auc,0.9968 ± 0.0040,0.9968 ± 0.0035,1.0000 ± 0.0000,0.9994 ± 0.0013
test_precision,0.9294 ± 0.0235,0.9287 ± 0.0232,0.9294 ± 0.0235,0.9294 ± 0.0235
train_precision,0.9294 ± 0.0059,0.9433 ± 0.0056,0.9406 ± 0.0158,0.9405 ± 0.0091
test_recall,1.0000 ± 0.0000,0.9875 ± 0.0250,1.0000 ± 0.0000,1.0000 ± 0.0000
train_recall,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000
test_f1,0.9633 ± 0.0129,0.9568 ± 0.0158,0.9633 ± 0.0129,0.9633 ± 0.0129
train_f1,0.9634 ± 0.0031,0.9708 ± 0.0030,0.9693 ± 0.0083,0.9693 ± 0.0048

# CRS >=2

In [19]:
y = targets["ae_summ_highestgrade_v2"]
y = y.astype('int8')
y[y<2] = 0
y[y>=2] = 1

y.value_counts()

ae_summ_highestgrade_v2
0    55
1    30
Name: count, dtype: int64

In [20]:
crs_2 = result_viewer(preprocessors, datasets, y)

Results for Logistic Regression:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.5152 ± 0.1684,0.5636 ± 0.1531,0.6030 ± 0.1225,0.5636 ± 0.1910
train_roc_auc,0.8909 ± 0.0284,0.9966 ± 0.0031,0.9977 ± 0.0023,1.0000 ± 0.0000
test_precision,0.5000 ± 0.2934,0.4700 ± 0.1166,0.4903 ± 0.2771,0.4037 ± 0.1163
train_precision,0.7542 ± 0.0594,0.9652 ± 0.0174,0.9590 ± 0.0253,1.0000 ± 0.0000
test_recall,0.2667 ± 0.1333,0.3333 ± 0.2108,0.4333 ± 0.2261,0.3667 ± 0.2449
train_recall,0.6000 ± 0.1007,0.9250 ± 0.0312,0.9667 ± 0.0167,0.9833 ± 0.0204
test_f1,0.3060 ± 0.1009,0.3634 ± 0.1605,0.4113 ± 0.1350,0.3516 ± 0.1636
train_f1,0.6666 ± 0.0828,0.9445 ± 0.0223,0.9628 ± 0.0201,0.9915 ± 0.0104

Results for Decision Tree:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.4121 ± 0.0305,0.4894 ± 0.1321,0.4818 ± 0.0721,0.6030 ± 0.1497
train_roc_auc,0.7810 ± 0.0420,0.8278 ± 0.0476,0.8148 ± 0.0257,0.8390 ± 0.0395
test_precision,0.1667 ± 0.1430,0.3200 ± 0.1904,0.3067 ± 0.1902,0.5048 ± 0.2956
train_precision,0.7062 ± 0.0864,0.8196 ± 0.1168,0.9149 ± 0.0751,0.7996 ± 0.1200
test_recall,0.2000 ± 0.1944,0.3333 ± 0.2108,0.2000 ± 0.1633,0.3667 ± 0.2449
train_recall,0.5667 ± 0.1307,0.6917 ± 0.1434,0.5167 ± 0.1074,0.6750 ± 0.2163
test_f1,0.1780 ± 0.1589,0.3135 ± 0.1873,0.2308 ± 0.1604,0.3667 ± 0.1432
train_f1,0.6113 ± 0.0618,0.7289 ± 0.0523,0.6493 ± 0.0772,0.6929 ± 0.1352

Results for Random Forest:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.6424 ± 0.1436,0.6394 ± 0.1280,0.6697 ± 0.1380,0.6364 ± 0.1494
train_roc_auc,0.9456 ± 0.0137,0.9640 ± 0.0101,0.9627 ± 0.0147,0.9873 ± 0.0118
test_precision,0.0000 ± 0.0000,0.3467 ± 0.3436,0.3667 ± 0.3712,0.1000 ± 0.2000
train_precision,1.0000 ± 0.0000,0.9567 ± 0.0530,0.9857 ± 0.0286,0.9882 ± 0.0235
test_recall,0.0000 ± 0.0000,0.1333 ± 0.0667,0.1333 ± 0.1247,0.1000 ± 0.2000
train_recall,0.3083 ± 0.0500,0.5750 ± 0.1067,0.4750 ± 0.0565,0.5833 ± 0.0950
test_f1,0.0000 ± 0.0000,0.1743 ± 0.0951,0.1944 ± 0.1859,0.1000 ± 0.2000
train_f1,0.4691 ± 0.0588,0.7089 ± 0.0730,0.6383 ± 0.0499,0.7284 ± 0.0731

# Outcome
CMR vs others

In [21]:
y = targets["surv_bestresponse_car"]

In [22]:
y.value_counts()

surv_bestresponse_car
1.0    63
2.0    12
4.0     8
0.0     2
Name: count, dtype: int64

Early Death: 0, CMR: 1, PMR:2, SD: 3, PD:4

In [23]:
y = y.astype('int8')

In [24]:
y[y != 1] = 0

In [25]:
y.value_counts()

surv_bestresponse_car
1    63
0    22
Name: count, dtype: int64

In [26]:
outcome = result_viewer(preprocessors, datasets, y)

Results for Logistic Regression:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.6649 ± 0.1252,0.5990 ± 0.1138,0.7356 ± 0.1169,0.6836 ± 0.0803
train_roc_auc,0.9476 ± 0.0192,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000
test_precision,0.7791 ± 0.0428,0.8116 ± 0.0612,0.8315 ± 0.1008,0.7848 ± 0.0488
train_precision,0.8900 ± 0.0247,0.9732 ± 0.0153,0.9961 ± 0.0078,0.9962 ± 0.0077
test_recall,0.8397 ± 0.0550,0.8577 ± 0.0571,0.7500 ± 0.1490,0.8090 ± 0.1293
train_recall,0.9603 ± 0.0127,1.0000 ± 0.0000,1.0000 ± 0.0000,0.9960 ± 0.0080
test_f1,0.8079 ± 0.0459,0.8303 ± 0.0207,0.7731 ± 0.0657,0.7925 ± 0.0749
train_f1,0.9238 ± 0.0188,0.9864 ± 0.0078,0.9980 ± 0.0040,0.9960 ± 0.0049

Results for Decision Tree:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.6688 ± 0.0815,0.4894 ± 0.0925,0.6059 ± 0.1021,0.5719 ± 0.0414
train_roc_auc,0.7747 ± 0.0191,0.8337 ± 0.0356,0.7936 ± 0.0621,0.8429 ± 0.0266
test_precision,0.8068 ± 0.0388,0.7493 ± 0.0484,0.7812 ± 0.0561,0.7705 ± 0.0576
train_precision,0.8613 ± 0.0103,0.8644 ± 0.0329,0.8638 ± 0.0352,0.8940 ± 0.0108
test_recall,0.9179 ± 0.0746,0.8731 ± 0.1429,0.8090 ± 0.1592,0.7615 ± 0.1394
train_recall,0.9601 ± 0.0335,0.9445 ± 0.0380,0.9684 ± 0.0268,0.9682 ± 0.0204
test_f1,0.8571 ± 0.0425,0.8036 ± 0.0889,0.7884 ± 0.1023,0.7548 ± 0.0638
train_f1,0.9077 ± 0.0160,0.9015 ± 0.0125,0.9123 ± 0.0165,0.9294 ± 0.0058

Results for Random Forest:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.6277 ± 0.1530,0.5269 ± 0.1458,0.6064 ± 0.1384,0.6197 ± 0.1006
train_roc_auc,0.9582 ± 0.0043,0.9562 ± 0.0091,0.9716 ± 0.0106,0.9904 ± 0.0080
test_precision,0.7412 ± 0.0288,0.7412 ± 0.0288,0.7456 ± 0.0423,0.7382 ± 0.0270
train_precision,0.7754 ± 0.0064,0.8134 ± 0.0223,0.8209 ± 0.0094,0.8082 ± 0.0175
test_recall,1.0000 ± 0.0000,1.0000 ± 0.0000,0.9077 ± 0.1231,0.9846 ± 0.0308
train_recall,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000
test_f1,0.8510 ± 0.0191,0.8510 ± 0.0191,0.8115 ± 0.0400,0.8432 ± 0.0191
train_f1,0.8735 ± 0.0040,0.8969 ± 0.0135,0.9016 ± 0.0057,0.8938 ± 0.0107

All the models in all the classification problems are hugely overfit, which is expected when we have fewer data points than features. This problem will be the focus of the next steps.