# Loading and Preprocessing

In [1]:
from data_loader import load_data

In [2]:
X_clinical,\
X_clinical_A,\
X_clinical_B,\
X_clinical_Delta,\
targets = load_data()

In [3]:
targets.head()

,surv_bestresponse_car,ae_summ_icans_v2,ae_summ_icans_highestgrade_v2,ae_summ_crs_v2,ae_summ_highestgrade_v2
FTC-UMCG-0001,1.0,1.0,1.0,1.0,1.0
FTC-UMCG-0003,4.0,0.0,0.0,1.0,1.0
FTC-UMCG-0004,4.0,1.0,3.0,1.0,2.0
FTC-UMCG-0005,2.0,1.0,2.0,1.0,1.0
FTC-UMCG-0006,1.0,0.0,0.0,1.0,2.0

In [4]:
datasets = {
    "Clinical": X_clinical,
    "Clinical_A": X_clinical_A,
    "Clinical_B": X_clinical_B,
    "Clinical_Delta": X_clinical_Delta
}

In [5]:
cat_cols = datasets['Clinical'].select_dtypes(exclude='number').columns.tolist()

In [6]:
# Using ColumnTransformer to apply different transformations to numeric and categorical columns
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

# Create a ColumnTransformer to apply StandardScaler to numeric columns and leave categorical columns unchanged
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', 'passthrough', cat_cols)],
        remainder= StandardScaler()
    
)

In [7]:
from model_eval import result_viewer

# ICANS 0,1

In [8]:
y = targets['ae_summ_icans_v2']

In [9]:
y.value_counts()

ae_summ_icans_v2
1.0    48
0.0    37
Name: count, dtype: int64

In [10]:
icans_1 = result_viewer(preprocessor, datasets, y)

Results for Logistic Regression:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.6265 ± 0.1846,0.6056 ± 0.1439,0.5790 ± 0.1794,0.4342 ± 0.1113
train_roc_auc,0.9176 ± 0.0235,0.9979 ± 0.0018,0.9993 ± 0.0009,1.0000 ± 0.0000
test_precision,0.6595 ± 0.1336,0.6498 ± 0.0686,0.6742 ± 0.1952,0.5418 ± 0.0913
train_precision,0.8527 ± 0.0362,0.9849 ± 0.0201,0.9847 ± 0.0205,1.0000 ± 0.0000
test_recall,0.7267 ± 0.1665,0.6889 ± 0.1390,0.6667 ± 0.1317,0.5444 ± 0.1421
train_recall,0.8960 ± 0.0277,0.9845 ± 0.0127,0.9791 ± 0.0197,0.9947 ± 0.0105
test_f1,0.6826 ± 0.1237,0.6631 ± 0.0865,0.6565 ± 0.1223,0.5372 ± 0.1035
train_f1,0.8734 ± 0.0271,0.9845 ± 0.0124,0.9817 ± 0.0134,0.9973 ± 0.0053

Results for Decision Tree:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.5781 ± 0.1011,0.5133 ± 0.1325,0.4807 ± 0.1202,0.5348 ± 0.0798
train_roc_auc,0.8040 ± 0.0121,0.8098 ± 0.0283,0.8189 ± 0.0248,0.8389 ± 0.0174
test_precision,0.6162 ± 0.0724,0.5691 ± 0.0987,0.5846 ± 0.0289,0.6657 ± 0.1918
train_precision,0.7883 ± 0.0360,0.7869 ± 0.0309,0.8440 ± 0.0861,0.8934 ± 0.0657
test_recall,0.6000 ± 0.1589,0.7289 ± 0.1029,0.8067 ± 0.1483,0.4867 ± 0.2166
train_recall,0.8385 ± 0.0714,0.8588 ± 0.0550,0.7977 ± 0.1783,0.7433 ± 0.1348
test_f1,0.5957 ± 0.0766,0.6367 ± 0.0953,0.6704 ± 0.0554,0.4929 ± 0.1683
train_f1,0.8098 ± 0.0310,0.8201 ± 0.0299,0.7985 ± 0.0657,0.7984 ± 0.0624

Results for Random Forest:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.6269 ± 0.0903,0.5213 ± 0.0948,0.6469 ± 0.0685,0.5028 ± 0.1689
train_roc_auc,0.9513 ± 0.0093,0.9527 ± 0.0118,0.9750 ± 0.0150,0.9807 ± 0.0059
test_precision,0.6219 ± 0.0861,0.5554 ± 0.0390,0.6059 ± 0.0988,0.5750 ± 0.0564
train_precision,0.7829 ± 0.0288,0.7721 ± 0.0330,0.8185 ± 0.0328,0.8462 ± 0.0390
test_recall,0.9133 ± 0.0827,0.7178 ± 0.2384,0.7778 ± 0.2389,0.8356 ± 0.1041
train_recall,0.9686 ± 0.0197,0.9791 ± 0.0197,0.9737 ± 0.0333,0.9843 ± 0.0128
test_f1,0.7390 ± 0.0842,0.6015 ± 0.1133,0.6464 ± 0.0814,0.6771 ± 0.0516
train_f1,0.8655 ± 0.0179,0.8628 ± 0.0207,0.8885 ± 0.0202,0.9093 ± 0.0177

## ICANS >=2

In [11]:
y = targets["ae_summ_icans_highestgrade_v2"]

In [12]:
y = y.astype('int8')

In [13]:
y[y<2] = 0
y[y>=2] = 1

In [14]:
y.value_counts()

ae_summ_icans_highestgrade_v2
0    52
1    33
Name: count, dtype: int64

In [15]:
icans_2 = result_viewer(preprocessor, datasets, y)

Results for Logistic Regression:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.5972 ± 0.1534,0.5843 ± 0.1283,0.5945 ± 0.0989,0.6395 ± 0.1365
train_roc_auc,0.9300 ± 0.0236,0.9975 ± 0.0030,0.9993 ± 0.0011,0.9982 ± 0.0032
test_precision,0.5267 ± 0.2030,0.5383 ± 0.1473,0.4667 ± 0.2530,0.5526 ± 0.0945
train_precision,0.8296 ± 0.0523,0.9701 ± 0.0150,0.9862 ± 0.0276,1.0000 ± 0.0000
test_recall,0.4619 ± 0.2138,0.4905 ± 0.1292,0.5714 ± 0.3938,0.6190 ± 0.2777
train_recall,0.7276 ± 0.0543,0.9775 ± 0.0298,0.9846 ± 0.0188,0.9550 ± 0.0436
test_f1,0.4830 ± 0.1956,0.4988 ± 0.1033,0.4674 ± 0.2591,0.5521 ± 0.1931
train_f1,0.7744 ± 0.0480,0.9736 ± 0.0194,0.9850 ± 0.0136,0.9765 ± 0.0230

Results for Decision Tree:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.5832 ± 0.1316,0.5235 ± 0.2287,0.4830 ± 0.0958,0.5165 ± 0.1944
train_roc_auc,0.7707 ± 0.0418,0.8198 ± 0.0538,0.8430 ± 0.0236,0.8274 ± 0.0284
test_precision,0.4686 ± 0.1113,0.5215 ± 0.2774,0.2824 ± 0.1540,0.4486 ± 0.1859
train_precision,0.6050 ± 0.0333,0.6900 ± 0.0572,0.8903 ± 0.0829,0.7218 ± 0.0803
test_recall,0.6524 ± 0.2911,0.5286 ± 0.2619,0.2429 ± 0.1478,0.4286 ± 0.2249
train_recall,0.8781 ± 0.1365,0.8245 ± 0.1087,0.5459 ± 0.1567,0.8248 ± 0.1851
test_f1,0.5171 ± 0.1729,0.4659 ± 0.1672,0.2562 ± 0.1471,0.4329 ± 0.1998
train_f1,0.7099 ± 0.0500,0.7491 ± 0.0710,0.6573 ± 0.0984,0.7467 ± 0.0759

Results for Random Forest:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.6216 ± 0.1329,0.4565 ± 0.1343,0.6097 ± 0.0900,0.5061 ± 0.0611
train_roc_auc,0.9565 ± 0.0165,0.9809 ± 0.0087,0.9778 ± 0.0068,0.9929 ± 0.0036
test_precision,0.4000 ± 0.4899,0.0500 ± 0.1000,0.6500 ± 0.3742,0.1667 ± 0.2108
train_precision,0.9889 ± 0.0222,0.9889 ± 0.0222,0.9757 ± 0.0297,1.0000 ± 0.0000
test_recall,0.0952 ± 0.1313,0.0333 ± 0.0667,0.2095 ± 0.1524,0.0619 ± 0.0762
train_recall,0.5009 ± 0.0920,0.6604 ± 0.1047,0.5991 ± 0.0565,0.6302 ± 0.0770
test_f1,0.1500 ± 0.2000,0.0400 ± 0.0800,0.2891 ± 0.1815,0.0889 ± 0.1089
train_f1,0.6589 ± 0.0753,0.7869 ± 0.0793,0.7409 ± 0.0462,0.7704 ± 0.0594

# CRS 0,1

In [16]:
y = targets["ae_summ_crs_v2"]

In [17]:
y.value_counts()

ae_summ_crs_v2
1.0    79
0.0     6
Name: count, dtype: int64

In [18]:
crs_1 = result_viewer(preprocessor, datasets, y)

Results for Logistic Regression:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.5083 ± 0.2753,0.2992 ± 0.3541,0.2575 ± 0.2021,0.3508 ± 0.2705
train_roc_auc,0.9956 ± 0.0055,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000
test_precision,0.9382 ± 0.0396,0.9249 ± 0.0251,0.9265 ± 0.0258,0.9222 ± 0.0241
train_precision,0.9606 ± 0.0115,1.0000 ± 0.0000,0.9938 ± 0.0076,0.9938 ± 0.0077
test_recall,0.9367 ± 0.0396,0.9367 ± 0.0396,0.9617 ± 0.0313,0.8992 ± 0.0746
train_recall,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000
test_f1,0.9363 ± 0.0211,0.9302 ± 0.0250,0.9435 ± 0.0248,0.9088 ± 0.0403
train_f1,0.9799 ± 0.0060,1.0000 ± 0.0000,0.9969 ± 0.0038,0.9969 ± 0.0039

Results for Decision Tree:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.5433 ± 0.2154,0.4625 ± 0.0364,0.3058 ± 0.2670,0.4558 ± 0.0423
train_roc_auc,0.8453 ± 0.0885,0.8348 ± 0.0974,0.9407 ± 0.0447,0.7649 ± 0.1066
test_precision,0.9349 ± 0.0397,0.9246 ± 0.0215,0.9357 ± 0.0032,0.9254 ± 0.0257
train_precision,0.9547 ± 0.0129,0.9755 ± 0.0155,0.9875 ± 0.0063,0.9605 ± 0.0073
test_recall,0.8992 ± 0.0494,0.9250 ± 0.0729,0.9242 ± 0.0466,0.9492 ± 0.0730
train_recall,0.9969 ± 0.0063,0.9968 ± 0.0063,0.9969 ± 0.0063,1.0000 ± 0.0000
test_f1,0.9157 ± 0.0343,0.9229 ± 0.0351,0.9294 ± 0.0248,0.9358 ± 0.0431
train_f1,0.9753 ± 0.0057,0.9859 ± 0.0058,0.9921 ± 0.0000,0.9798 ± 0.0038

Results for Random Forest:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.6125 ± 0.1212,0.5283 ± 0.2638,0.4725 ± 0.3896,0.4037 ± 0.2790
train_roc_auc,0.9994 ± 0.0013,0.9917 ± 0.0077,0.9992 ± 0.0016,0.9960 ± 0.0047
test_precision,0.9294 ± 0.0235,0.9294 ± 0.0235,0.9294 ± 0.0235,0.9294 ± 0.0235
train_precision,0.9322 ± 0.0070,0.9461 ± 0.0071,0.9377 ± 0.0056,0.9434 ± 0.0107
test_recall,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000
train_recall,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000
test_f1,0.9633 ± 0.0129,0.9633 ± 0.0129,0.9633 ± 0.0129,0.9633 ± 0.0129
train_f1,0.9649 ± 0.0037,0.9723 ± 0.0038,0.9678 ± 0.0030,0.9708 ± 0.0057

# CRS >=2

In [19]:
y = targets["ae_summ_highestgrade_v2"]
y = y.astype('int8')
y[y<2] = 0
y[y>=2] = 1

y.value_counts()

ae_summ_highestgrade_v2
0    55
1    30
Name: count, dtype: int64

In [20]:
crs_2 = result_viewer(preprocessor, datasets, y)

Results for Logistic Regression:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.5364 ± 0.1070,0.5091 ± 0.0912,0.6061 ± 0.0852,0.5788 ± 0.1056
train_roc_auc,0.9002 ± 0.0213,0.9981 ± 0.0025,0.9975 ± 0.0020,1.0000 ± 0.0000
test_precision,0.4617 ± 0.0960,0.4967 ± 0.1551,0.4669 ± 0.2865,0.3638 ± 0.0787
train_precision,0.7487 ± 0.0674,0.9666 ± 0.0167,0.9833 ± 0.0205,1.0000 ± 0.0000
test_recall,0.4000 ± 0.0816,0.3667 ± 0.1247,0.4333 ± 0.2708,0.3667 ± 0.1247
train_recall,0.5667 ± 0.0677,0.9583 ± 0.0264,0.9583 ± 0.0373,0.9667 ± 0.0312
test_f1,0.4215 ± 0.0694,0.4190 ± 0.1368,0.3959 ± 0.1690,0.3537 ± 0.0909
train_f1,0.6434 ± 0.0598,0.9622 ± 0.0160,0.9702 ± 0.0219,0.9828 ± 0.0162

Results for Decision Tree:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.4818 ± 0.0446,0.6106 ± 0.0984,0.4652 ± 0.1519,0.4621 ± 0.1074
train_roc_auc,0.7347 ± 0.0543,0.8391 ± 0.0345,0.7787 ± 0.0282,0.8549 ± 0.0425
test_precision,0.1371 ± 0.1718,0.4883 ± 0.3325,0.4000 ± 0.4899,0.2333 ± 0.2000
train_precision,0.6335 ± 0.3380,0.8730 ± 0.1324,0.9607 ± 0.0510,0.9324 ± 0.0662
test_recall,0.1333 ± 0.1633,0.3333 ± 0.2357,0.1000 ± 0.1333,0.1667 ± 0.1826
train_recall,0.4333 ± 0.2771,0.6000 ± 0.2577,0.4583 ± 0.0950,0.5583 ± 0.2051
test_f1,0.1343 ± 0.1654,0.3317 ± 0.1803,0.1571 ± 0.2040,0.1889 ± 0.1846
train_f1,0.4827 ± 0.2569,0.6537 ± 0.1473,0.6116 ± 0.0777,0.6663 ± 0.1565

Results for Random Forest:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.6212 ± 0.1348,0.6030 ± 0.1144,0.6273 ± 0.1052,0.6121 ± 0.1226
train_roc_auc,0.9564 ± 0.0094,0.9538 ± 0.0132,0.9659 ± 0.0138,0.9809 ± 0.0195
test_precision,0.2000 ± 0.4000,0.1800 ± 0.1568,0.5667 ± 0.3887,0.2500 ± 0.3873
train_precision,1.0000 ± 0.0000,0.9765 ± 0.0471,0.9732 ± 0.0329,0.9789 ± 0.0421
test_recall,0.0333 ± 0.0667,0.1333 ± 0.1247,0.2000 ± 0.1633,0.0667 ± 0.0816
train_recall,0.2917 ± 0.0645,0.6000 ± 0.0425,0.5750 ± 0.0312,0.5667 ± 0.0898
test_f1,0.0571 ± 0.1143,0.1527 ± 0.1383,0.2849 ± 0.2154,0.0971 ± 0.1220
train_f1,0.4480 ± 0.0729,0.7416 ± 0.0318,0.7221 ± 0.0246,0.7116 ± 0.0609

# Outcome
CMR vs others

In [21]:
y = targets["surv_bestresponse_car"]

In [22]:
y.value_counts()

surv_bestresponse_car
1.0    63
2.0    12
4.0     8
0.0     2
Name: count, dtype: int64

Early Death: 0, CMR: 1, PMR:2, SD: 3, PD:4

In [23]:
y = y.astype('int8')

In [24]:
y[y != 1] = 0

In [25]:
y.value_counts()

surv_bestresponse_car
1    63
0    22
Name: count, dtype: int64

In [26]:
outcome = result_viewer(preprocessor, datasets, y)

Results for Logistic Regression:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.7146 ± 0.0635,0.5190 ± 0.0874,0.6295 ± 0.1074,0.7156 ± 0.1584
train_roc_auc,0.9509 ± 0.0091,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000
test_precision,0.8009 ± 0.0687,0.7755 ± 0.0528,0.8001 ± 0.0535,0.8059 ± 0.0746
train_precision,0.8972 ± 0.0137,0.9731 ± 0.0154,0.9922 ± 0.0095,1.0000 ± 0.0000
test_recall,0.9205 ± 0.0718,0.9205 ± 0.0718,0.7782 ± 0.1777,0.8551 ± 0.1100
train_recall,0.9682 ± 0.0098,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000
test_f1,0.8523 ± 0.0349,0.8397 ± 0.0456,0.7729 ± 0.0940,0.8268 ± 0.0783
train_f1,0.9313 ± 0.0074,0.9863 ± 0.0079,0.9961 ± 0.0048,1.0000 ± 0.0000

Results for Decision Tree:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.5309 ± 0.0751,0.4810 ± 0.0900,0.5162 ± 0.1086,0.4631 ± 0.0907
train_roc_auc,0.7680 ± 0.0251,0.8271 ± 0.0499,0.8208 ± 0.0439,0.8428 ± 0.0610
test_precision,0.7601 ± 0.0250,0.7553 ± 0.0324,0.7570 ± 0.0315,0.7480 ± 0.0225
train_precision,0.8573 ± 0.0145,0.8807 ± 0.0532,0.8888 ± 0.0351,0.8819 ± 0.0469
test_recall,0.9038 ± 0.0601,0.8859 ± 0.0988,0.8744 ± 0.0911,0.8423 ± 0.1608
train_recall,0.9761 ± 0.0294,0.9489 ± 0.0489,0.9482 ± 0.0676,0.9762 ± 0.0232
test_f1,0.8249 ± 0.0318,0.8136 ± 0.0540,0.8070 ± 0.0290,0.7829 ± 0.0796
train_f1,0.9126 ± 0.0155,0.9108 ± 0.0129,0.9147 ± 0.0181,0.9253 ± 0.0171

Results for Random Forest:

,Clinical,Clinical_A,Clinical_B,Clinical_Delta
test_roc_auc,0.7118 ± 0.0947,0.5141 ± 0.1259,0.5813 ± 0.1205,0.5995 ± 0.1534
train_roc_auc,0.9552 ± 0.0078,0.9560 ± 0.0084,0.9545 ± 0.0151,0.9900 ± 0.0086
test_precision,0.7412 ± 0.0288,0.7375 ± 0.0338,0.7482 ± 0.0369,0.7309 ± 0.0358
train_precision,0.7778 ± 0.0071,0.8188 ± 0.0259,0.8433 ± 0.0214,0.8091 ± 0.0369
test_recall,1.0000 ± 0.0000,0.9833 ± 0.0333,0.9846 ± 0.0308,0.9513 ± 0.0398
train_recall,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000,1.0000 ± 0.0000
test_f1,0.8510 ± 0.0191,0.8427 ± 0.0322,0.8491 ± 0.0179,0.8265 ± 0.0362
train_f1,0.8750 ± 0.0045,0.9001 ± 0.0156,0.9148 ± 0.0127,0.8940 ± 0.0225

All the models in all the classification problems are hugely overfit, which is expected when we have fewer data points than features. This problem will be the focus of the next steps.